### ISSUE TITLE
iOS Feature - UIUX x Data in Board Section of Explore module

### ISSUE THREAD

**Issue by Vince-Ku** [No-57/SCSH_3C_iOS#31]
# Feature

### Description
Implement the feature in the `Board` section of the `Explore` module.

### Tasks
- [x]  Static UI implement
- [x]  Static UI optimization
- [x]  User's interaction handle
