### ISSUE TITLE
iOS Feature - UIUX x Data in Distributor Section of Explore module

### ISSUE THREAD

**Issue by Vince-Ku** [No-57/SCSH_3C_iOS#41]
# Feature

### Description
Implement the feature in the `Distributor` section of the `Explore` module.

### Tasks
- [x] Static UI implement
- [x] Static UI optimization
- [x] User's interaction handle (like button remaining)
- [x] Distributor Repository Facade

---

## Distributor API
Description: get all distributors.
``` shell
GET https://{domainhost}/distributors
?code={code}&limit={limit}
```
 #### Response
 ``` JSON
"data": [
    { "id": 123,
      "name": "PChome",
      "description": "台灣電商龍頭",
      "brand_image": "https://example.brandImage.jpg",
      "products": [
          { "id":123,
            "image":"https://example.example.jpg"}
       ]},
]
```
